

const AboutPage = () => {
  return (
    <div>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ducimus, dolorem. Voluptates, repellendus mollitia. Repellendus nobis voluptatem velit minima officiis sint quidem ratione saepe obcaecati cum dolore, sunt dolores pariatur, molestiae voluptates ullam eius accusamus numquam quo libero, nihil facilis consequuntur! Numquam, ipsa culpa? Accusamus neque repellat commodi optio eaque ipsa quos expedita sunt, nostrum ullam, harum eveniet maxime velit officiis sapiente quibusdam enim corrupti dolore deserunt iure vel vitae. Placeat laboriosam asperiores quis ad accusantium amet, blanditiis voluptate. Soluta aperiam voluptate eius amet sint laborum neque ad! Nobis quaerat, tempora perferendis error inventore quas, nulla sapiente accusamus in suscipit pariatur voluptates distinctio unde ipsum repudiandae dolores consequatur! Aliquid facere sed nostrum vero quae? Eius minima libero fugit? Cumque veritatis recusandae consequatur. Rem consequuntur, optio porro voluptatem repellat exercitationem expedita consectetur harum, nobis aut aliquid ut obcaecati dignissimos. Beatae facilis iusto possimus omnis atque natus blanditiis corporis error quidem adipisci? Recusandae quod atque ut ex eius consequatur illum sunt nemo aliquam dolore. Neque culpa dolorum laborum velit nihil mollitia aliquam soluta quasi assumenda, quas perspiciatis earum? Nesciunt, libero consequatur, nobis necessitatibus qui totam, blanditiis accusamus mollitia sapiente vero perferendis est non minus praesentium architecto distinctio ad tempora inventore maiores omnis fuga quod. Veniam vitae reprehenderit doloremque, ratione tempora ducimus. Maiores rerum at quia id, labore voluptas culpa consequuntur saepe veniam reprehenderit maxime. Suscipit alias quo sequi odit? Harum a ab dolore doloribus minima quia ratione. Molestiae corrupti ipsa commodi, odio itaque quas, repellendus atque assumenda vel veniam perspiciatis voluptatem labore iusto qui! Autem unde accusamus, voluptate nam quo voluptatum itaque quam fugiat dicta inventore veritatis similique harum ipsum ad culpa perferendis at, cum quidem est in? Tempora, aut, atque perferendis reprehenderit aperiam aliquid dicta molestiae adipisci officia recusandae delectus voluptatem temporibus. Cum, debitis! Accusamus odit ex alias excepturi est, aspernatur enim!</p>
    </div>
  )
}

export default AboutPage
